SAUDI_LOCATIONS = [
    {
        "code": "riyadh",
        "name_en": "Riyadh",
        "name_ar": "الرياض",
        "cities": [
            {"code": "riyadh_city", "name_en": "Riyadh", "name_ar": "الرياض"},
            {"code": "diriyah", "name_en": "Diriyah", "name_ar": "الدرعية"},
            {"code": "al_kharj", "name_en": "Al Kharj", "name_ar": "الخرج"},
            {"code": "dawadmi", "name_en": "Dawadmi", "name_ar": "الدوادمي"},
            {"code": "majmaah", "name_en": "Al Majma'ah", "name_ar": "المجمعة"},
            {"code": "shaqqa", "name_en": "Shaqra", "name_ar": "شقراء"},
            {"code": "afif", "name_en": "Afif", "name_ar": "عفيف"},
        ],
    },
    {
        "code": "makkah",
        "name_en": "Makkah",
        "name_ar": "مكة المكرمة",
        "cities": [
            {"code": "makkah_city", "name_en": "Makkah", "name_ar": "مكة المكرمة"},
            {"code": "jeddah", "name_en": "Jeddah", "name_ar": "جدة"},
            {"code": "taif", "name_en": "Taif", "name_ar": "الطائف"},
            {"code": "rabigh", "name_en": "Rabigh", "name_ar": "رابغ"},
            {"code": "al_qunfudhah", "name_en": "Al Qunfudhah", "name_ar": "القنفذة"},
            {"code": "al_lith", "name_en": "Al Lith", "name_ar": "الليث"},
        ],
    },
    {
        "code": "madinah",
        "name_en": "Madinah",
        "name_ar": "المدينة المنورة",
        "cities": [
            {"code": "madinah_city", "name_en": "Madinah", "name_ar": "المدينة المنورة"},
            {"code": "yanbu", "name_en": "Yanbu", "name_ar": "ينبع"},
            {"code": "al_ula", "name_en": "AlUla", "name_ar": "العلا"},
            {"code": "badr", "name_en": "Badr", "name_ar": "بدر"},
            {"code": "khaybar", "name_en": "Khaybar", "name_ar": "خيبر"},
        ],
    },
    {
        "code": "eastern_province",
        "name_en": "Eastern Province",
        "name_ar": "المنطقة الشرقية",
        "cities": [
            {"code": "dammam", "name_en": "Dammam", "name_ar": "الدمام"},
            {"code": "khobar", "name_en": "Al Khobar", "name_ar": "الخبر"},
            {"code": "dhahran", "name_en": "Dhahran", "name_ar": "الظهران"},
            {"code": "jubail", "name_en": "Jubail", "name_ar": "الجبيل"},
            {"code": "al_hofuf", "name_en": "Al Hofuf", "name_ar": "الهفوف"},
            {"code": "al_mubarraz", "name_en": "Al Mubarraz", "name_ar": "المبرز"},
            {"code": "qatif", "name_en": "Qatif", "name_ar": "القطيف"},
            {"code": "khafji", "name_en": "Khafji", "name_ar": "الخفجي"},
            {"code": "hafr_al_batin", "name_en": "Hafar Al Batin", "name_ar": "حفر الباطن"},
        ],
    },
    {
        "code": "qassim",
        "name_en": "Al Qassim",
        "name_ar": "القصيم",
        "cities": [
            {"code": "buraydah", "name_en": "Buraydah", "name_ar": "بريدة"},
            {"code": "unaizah", "name_en": "Unaizah", "name_ar": "عنيزة"},
            {"code": "al_rass", "name_en": "Al Rass", "name_ar": "الرس"},
            {"code": "al_bukayriyah", "name_en": "Al Bukayriyah", "name_ar": "البكيرية"},
            {"code": "al_badayi", "name_en": "Al Badayea", "name_ar": "البدائع"},
        ],
    },
    {
        "code": "asir",
        "name_en": "Asir",
        "name_ar": "عسير",
        "cities": [
            {"code": "abha", "name_en": "Abha", "name_ar": "أبها"},
            {"code": "khamis_mushait", "name_en": "Khamis Mushait", "name_ar": "خميس مشيط"},
            {"code": "bisha", "name_en": "Bisha", "name_ar": "بيشة"},
            {"code": "muhayil_asir", "name_en": "Muhayil Asir", "name_ar": "محايل عسير"},
            {"code": "ahad_rufaidah", "name_en": "Ahad Rafidah", "name_ar": "أحد رفيدة"},
        ],
    },
    {
        "code": "tabuk",
        "name_en": "Tabuk",
        "name_ar": "تبوك",
        "cities": [
            {"code": "tabuk_city", "name_en": "Tabuk", "name_ar": "تبوك"},
            {"code": "duba", "name_en": "Duba", "name_ar": "ضباء"},
            {"code": "al_wajh", "name_en": "Al Wajh", "name_ar": "الوجه"},
            {"code": "tayma", "name_en": "Tayma", "name_ar": "تيماء"},
            {"code": "haql", "name_en": "Haql", "name_ar": "حقل"},
        ],
    },
    {
        "code": "hail",
        "name_en": "Ha'il",
        "name_ar": "حائل",
        "cities": [
            {"code": "hail_city", "name_en": "Ha'il", "name_ar": "حائل"},
            {"code": "baqaa", "name_en": "Baqaa", "name_ar": "بقعاء"},
            {"code": "al_ghazalah", "name_en": "Al Ghazalah", "name_ar": "الغزالة"},
            {"code": "ash_shinan", "name_en": "Ash Shinan", "name_ar": "الشنان"},
        ],
    },
    {
        "code": "northern_borders",
        "name_en": "Northern Borders",
        "name_ar": "الحدود الشمالية",
        "cities": [
            {"code": "arar", "name_en": "Arar", "name_ar": "عرعر"},
            {"code": "rafha", "name_en": "Rafha", "name_ar": "رفحاء"},
            {"code": "turaif", "name_en": "Turaif", "name_ar": "طريف"},
            {"code": "al_uwayqilah", "name_en": "Al Uwayqilah", "name_ar": "العويقيلة"},
        ],
    },
    {
        "code": "jazan",
        "name_en": "Jazan",
        "name_ar": "جازان",
        "cities": [
            {"code": "jazan_city", "name_en": "Jazan", "name_ar": "جازان"},
            {"code": "sabya", "name_en": "Sabya", "name_ar": "صبيا"},
            {"code": "abu_arish", "name_en": "Abu Arish", "name_ar": "أبو عريش"},
            {"code": "samtah", "name_en": "Samtah", "name_ar": "صامطة"},
            {"code": "farasan", "name_en": "Farasan", "name_ar": "فرسان"},
        ],
    },
    {
        "code": "najran",
        "name_en": "Najran",
        "name_ar": "نجران",
        "cities": [
            {"code": "najran_city", "name_en": "Najran", "name_ar": "نجران"},
            {"code": "sharurah", "name_en": "Sharurah", "name_ar": "شرورة"},
            {"code": "hubuna", "name_en": "Hubuna", "name_ar": "حبونا"},
            {"code": "badr_al_janub", "name_en": "Badr Al Janub", "name_ar": "بدر الجنوب"},
        ],
    },
    {
        "code": "al_bahah",
        "name_en": "Al Bahah",
        "name_ar": "الباحة",
        "cities": [
            {"code": "al_bahah_city", "name_en": "Al Bahah", "name_ar": "الباحة"},
            {"code": "baljurashi", "name_en": "Baljurashi", "name_ar": "بلجرشي"},
            {"code": "al_mandaq", "name_en": "Al Mandaq", "name_ar": "المندق"},
            {"code": "al_mikhwah", "name_en": "Al Mikhwah", "name_ar": "المخواة"},
        ],
    },
    {
        "code": "al_jouf",
        "name_en": "Al Jouf",
        "name_ar": "الجوف",
        "cities": [
            {"code": "sakaka", "name_en": "Sakaka", "name_ar": "سكاكا"},
            {"code": "dumat_al_jandal", "name_en": "Dumat Al Jandal", "name_ar": "دومة الجندل"},
            {"code": "qurayyat", "name_en": "Al Qurayyat", "name_ar": "القريات"},
            {"code": "tabarjal", "name_en": "Tabarjal", "name_ar": "طبرجل"},
        ],
    },
]