"""add meal plan items

Revision ID: 1fee74ee6808
Revises: 38e071b5103e
Create Date: 2026-07-07 23:22:18.623415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fee74ee6808'
down_revision: Union[str, Sequence[str], None] = '38e071b5103e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('GENERAL', 'ORDER', 'DELIVERY', 'SUBSCRIPTION', 'PAYMENT', 'PROMOTION', name='notificationtype'),
               existing_nullable=False)
    op.alter_column('notifications', 'channel',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('IN_APP', 'EMAIL', 'SMS', 'WHATSAPP', name='notificationchannel'),
               existing_nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('notifications', 'channel',
               existing_type=sa.Enum('IN_APP', 'EMAIL', 'SMS', 'WHATSAPP', name='notificationchannel'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.Enum('GENERAL', 'ORDER', 'DELIVERY', 'SUBSCRIPTION', 'PAYMENT', 'PROMOTION', name='notificationtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
