"""add payments table

Revision ID: 423c5e16cbb3
Revises: e07b3aa7e4e4
Create Date: 2026-07-08 02:40:07.855320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423c5e16cbb3'
down_revision: Union[str, Sequence[str], None] = 'e07b3aa7e4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('STRIPE', name='paymentprovider'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'CANCELLED', name='paymentrecordstatus'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('checkout_url', sa.String(length=1000), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('GENERAL', 'ORDER', 'DELIVERY', 'SUBSCRIPTION', 'PAYMENT', 'PROMOTION', name='notificationtype'),
               existing_nullable=False)
    op.alter_column('notifications', 'channel',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('IN_APP', 'EMAIL', 'SMS', 'WHATSAPP', name='notificationchannel'),
               existing_nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('notifications', 'channel',
               existing_type=sa.Enum('IN_APP', 'EMAIL', 'SMS', 'WHATSAPP', name='notificationchannel'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.Enum('GENERAL', 'ORDER', 'DELIVERY', 'SUBSCRIPTION', 'PAYMENT', 'PROMOTION', name='notificationtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
