"""initial tables

Revision ID: 5b8152bf471f
Revises: 
Create Date: 2026-07-05 21:18:33.578201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8152bf471f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_categories', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('height_cm', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('fitness_goal', sa.Enum('WEIGHT_LOSS', 'MUSCLE_GAIN', 'MAINTENANCE', 'HEALTHY_LIFESTYLE', name='fitnessgoal'), nullable=True))
    op.add_column('users', sa.Column('dietary_preference', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('allergies', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('email_otp', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('email_otp_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_reset_otp', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('password_reset_otp_expires_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('users', 'password_reset_otp_expires_at')
    op.drop_column('users', 'password_reset_otp')
    op.drop_column('users', 'email_otp_expires_at')
    op.drop_column('users', 'email_otp')
    op.drop_column('users', 'allergies')
    op.drop_column('users', 'dietary_preference')
    op.drop_column('users', 'fitness_goal')
    op.drop_column('users', 'weight_kg')
    op.drop_column('users', 'height_cm')
    op.drop_column('users', 'age')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'address')
    op.drop_column('users', 'location')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('meal_categories', 'image_url')
    # ### end Alembic commands ###
