"""add meal selections

Revision ID: e07b3aa7e4e4
Revises: 1fee74ee6808
Create Date: 2026-07-07 23:43:15.778213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07b3aa7e4e4'
down_revision: Union[str, Sequence[str], None] = '1fee74ee6808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('meal_time', sa.String(length=50), nullable=False),
    sa.Column('is_skipped', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'subscription_id', 'day_number', 'meal_time', name='unique_user_subscription_day_meal_time')
    )
    op.create_index(op.f('ix_meal_selections_id'), 'meal_selections', ['id'], unique=False)
    op.create_index(op.f('ix_meal_selections_meal_id'), 'meal_selections', ['meal_id'], unique=False)
    op.create_index(op.f('ix_meal_selections_plan_id'), 'meal_selections', ['plan_id'], unique=False)
    op.create_index(op.f('ix_meal_selections_subscription_id'), 'meal_selections', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_meal_selections_user_id'), 'meal_selections', ['user_id'], unique=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('GENERAL', 'ORDER', 'DELIVERY', 'SUBSCRIPTION', 'PAYMENT', 'PROMOTION', name='notificationtype'),
               existing_nullable=False)
    op.alter_column('notifications', 'channel',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('IN_APP', 'EMAIL', 'SMS', 'WHATSAPP', name='notificationchannel'),
               existing_nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('notifications', 'channel',
               existing_type=sa.Enum('IN_APP', 'EMAIL', 'SMS', 'WHATSAPP', name='notificationchannel'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.Enum('GENERAL', 'ORDER', 'DELIVERY', 'SUBSCRIPTION', 'PAYMENT', 'PROMOTION', name='notificationtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_meal_selections_user_id'), table_name='meal_selections')
    op.drop_index(op.f('ix_meal_selections_subscription_id'), table_name='meal_selections')
    op.drop_index(op.f('ix_meal_selections_plan_id'), table_name='meal_selections')
    op.drop_index(op.f('ix_meal_selections_meal_id'), table_name='meal_selections')
    op.drop_index(op.f('ix_meal_selections_id'), table_name='meal_selections')
    op.drop_table('meal_selections')
    # ### end Alembic commands ###
